### ISSUE TITLE
Elastic Search integration

### ISSUE THREAD

**Issue by Fewiel** [Fewiel/EnvironmentServer#25]
Integrate Elasticsearch with docker

```
version: "3"

services:
        elasticsearch:
        image: elasticsearch: 6.8.1
                  container_name: elasticsearch681
                  hostname: EnvName - elastic
                  networks:
            -web
                  environment:
            -"EA_JAVA_OPTS=-Xms512m -Xms512m"
            - discovery.type = single - node

            networks:
        web:
        external: false
```

cron to sutdown at night  
possibility to make it persistent
